### PR TITLE
Generate a base class for FitsImage so that the algorithm can work directly on numpy arrays

### PR DESCRIPTION
**Pull request by tmolteno**
Hi There,

Many thanks for creating PyMORESANE.

I'm working on the TART radio telescope - its an open-source 24-element design that uses a RESTful API to get visibilities. (github.com/tmolteno/TART), and has a web front end, as well as a python imaging front end.

These changes allow us to use moresane as one of the imaging algorithms from the python imaging front end (it works, although I haven't tuned parameters yet.). 

Changes:
* Moved to astropy.io.fits from pyfits
* Add a new base class DataImage, that holds the methods for managing the data once its in arrays. This bypasses FITS files.
* Placed a try-except around some hdu header stuff in the restore method that was failing.

### CODE REVIEW

**Comment by JSKenyon** [comment]
Hi @tmolteno! I am glad that you are getting some use out of PyMORESANE. It has been quite a while since I last worked on this project - I assume that you have tested your PR to ensure that setup works correctly? If so, I will happily merge this.

**Comment by tmolteno** [comment]
Hi there. Thanks for merging. MORESANE is running pretty well. I am testing on debian testing with python 2.7, and using snapshot dirty images and beams.

Our code using the modified PyMORESANE is [https://raw.githubusercontent.com/tmolteno/TART/master/software/python/tart_tools/bin/tart_image]. It has been very easy to incorporate. Currently the images produced are better than dirty images, but not working as well as difmap.

If you're in SA, one of our scopes is being installed at Stellenbosch. I think the components have are in customs as of today :)

**Comment by tmolteno** [comment]
If you wish to test the modified moresane using live data from one of our telescopes (assuming PyMORESANE is installed)

    pip install tart_tools

The following command will generate an image:

    tart_image --moresane --display --show-sources

**Comment by o-smirnov** [comment]
@tmolteno, that looks pretty awesome! 

@JSKenyon, just as a sanity check, can we verify that the original FITS mode still runs (really need to ask @bennahugo to set up a jenkins test for us...)?

**Comment by tmolteno** [comment]
I have done a brief sanity check using FITS files from our scope. I will commit a couple of FITS images (dirty and beam) from one of the TART telescopes and a basic test using runsane.

**Pull request merged**
